version: '3'
services:
  nginxproxymanager:
    container_name: nginxproxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      webserver-network:
        ipv4_address: 10.0.0.2
        aliases:
          - nginxproxymanager


networks:
  webserver-network:
    name: webservernet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24